services:
  Sengped_app:
    image: prawee/strapi:latest
    container_name: Sengped_App
    depends_on:
      Sengped_Dab:
        condition: service_healthy
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: ${DAB_HOST}
      DATABASE_PORT: ${DAB_PORT}
      DATABASE_NAME: ${DAB_NAME}
      DATABASE_USERNAME: ${DAB_USER}
      DATABASE_PASSWORD: ${DAB_PASS}
    ports:
      - ${APP_PORT}:${STRAPI_PORT}
