services:
  Sengped_Dab:
    image: postgres:latest
    container_name: Sengped_Dab
    ports:
      - "${DAB_PORT}:5432"
    environment:
      POSTGRES_USER: ${DAB_USER}
      POSTGRES_PASSWORD: ${DAB_PASS}
      POSTGRES_DB: ${DAB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10