services:
  Sengped_Dab:
    image: postgres:latest
    container_name: Sengped_Dab
    ports:
      - "${DAB_PORT_HOST:-55432}:5432"
    environment:
      POSTGRES_USER: ${DAB_USER}
      POSTGRES_PASSWORD: ${DAB_PASS}
      POSTGRES_DB: ${DAB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db-data:
