services:
  webserver:
    image: nginx:alpine
    container_name: Sengped_webserver
    restart: unless-stopped
    depends_on:
      - Sengped_app
    ports:
      - "${NGINX_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro